query getCourses(
  $perPage: Int!
  $page: Int!
  $yearStart: Int!
  $yearEnd: Int!
) {
  coursesConnection(
    perPage: $perPage
    page: $page
    courseLevels: [NOLEVEL, PRIMUGRD, UGRDGRAD, PRIMGRAD] # skip 300-level
    semesterRange: {
      start: { termName: FALL, termYear: $yearStart }
      end: { termName: SPRING, termYear: $yearEnd }
    }
  ) {
    totalCount
    nodes {
      id
      externalCourseId
      qGuideCourseId
      title
      subject
      subjectDescription
      catalogNumber
      courseLevel
      academicGroup
      semester
      academicYear
      classSection
      component
      componentFiltered
      courseDescription
      courseDescriptionLong
      courseAttributes {
        crseAttribute
        crseAttributeDescription
        crseAttrValue
        crseAttrValueDescription
      }
      courseInstructors {
        id
        displayName
        email
        instructorRole
        firstName
        middleName
        lastName
      }
      courseMeetingPatterns {
        id
        meetingTimeStartTod
        meetingTimeEndTod
        startDate
        endDate
        meetsOnMonday
        meetsOnTuesday
        meetsOnWednesday
        meetsOnThursday
        meetsOnFriday
        meetsOnSaturday
        meetsOnSunday
      }
      termCode
      unitsMaximum
    }
  }
}
