query getCourses($query: String, $perPage: Int!, $page: Int!) {
  coursesConnection(
    basic: $query
    perPage: $perPage
    page: $page
    courseLevels: [NOLEVEL, PRIMUGRD, UGRDGRAD, PRIMGRAD] # skip 300-level
    semesterRange: {
      start: { termName: FALL, termYear: 2018 }
      end: { termName: SPRING, termYear: 2030 }
    }
  ) {
    totalCount
    nodes {
      id
      externalCourseId
      qGuideCourseId
      title
      subject
      subjectDescription
      catalogNumber
      courseLevel
      academicGroup
      semester
      academicYear
      classSection
      component
      componentFiltered
      courseDescription
      courseDescriptionLong
      courseInstructors {
        id
        displayName
        email
        instructorRole
        firstName
        middleName
        lastName
      }
      courseMeetingPatterns {
        id
        meetingTimeStartTod
        meetingTimeEndTod
        startDate
        endDate
        meetsOnMonday
        meetsOnTuesday
        meetsOnWednesday
        meetsOnThursday
        meetsOnFriday
        meetsOnSaturday
        meetsOnSunday
      }
      termCode
      unitsMaximum
    }
  }
}
