name: CI

on: [push, pull_request]

jobs:
  go:
    name: Go build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - run: go build

  web:
    name: Frontend build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci

      - run: npm run format:check

      - run: npm run check

      - run: npm run build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [go, web]
    concurrency:
      group: deploy
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v2

      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: deploy --remote-only
