name: Format checker
on: push
jobs:
  ensure-gofmt:
    name: Ensure gofmt matches
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run gofmt
        run: gofmt -s -w .

      - name: Ensure gofmt matches
        run: git diff --exit-code
