name: Format checker
on: push
jobs:
  compare-gofmt:
    name: Compare gofmt output
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Compare gofmt output
        shell: bash
        run: |
          : # Calculate gofmt diff.
          gofmt -d -l -s . |
          : # If it exists, show diff and fail. Otherwise succeed.
          tee >([ -z "$(head -c1)" ])
