name: Format checker
on: push
jobs:
  compare-gofmt:
    name: Compare gofmt output
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run gofmt
        run: gofmt -s -w .

      - name: Show differences
        run: git diff --exit-code
