name: Format suggester
on: pull_request
jobs:
  suggest-gofmt:
    name: Suggest gofmt changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run gofmt
        run: gofmt -s -w .

      - name: Suggest gofmt changes # in the form of a PR review
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
          filter_mode: nofilter
